/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppTenantIdRouteImport } from './routes/_app.$tenantId'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as ApiHealthcheckRouteImport } from './routes/api/healthcheck'
import { Route as WidgetBadgeRouteImport } from './routes/widget/badge'
import { Route as WidgetCounterRouteImport } from './routes/widget/counter'
import { Route as WidgetRealtimeRouteImport } from './routes/widget/realtime'
import { Route as WidgetTestRouteImport } from './routes/widget/test'
import { Route as AppTenantIdIndexRouteImport } from './routes/_app.$tenantId.index'
import { Route as AppTenantIdShopIdRouteImport } from './routes/_app.$tenantId.$shopId'
import { Route as AppTenantIdShopIdIndexRouteImport } from './routes/_app.$tenantId.$shopId.index'
import { Route as AppTenantIdShopIdDashboardsRouteImport } from './routes/_app.$tenantId.$shopId.dashboards'
import { Route as AppTenantIdShopIdInsightsRouteImport } from './routes/_app.$tenantId.$shopId.insights'
import { Route as AppTenantIdShopIdPagesRouteImport } from './routes/_app.$tenantId.$shopId.pages'
import { Route as AppTenantIdShopIdRealtimeRouteImport } from './routes/_app.$tenantId.$shopId.realtime'
import { Route as AppTenantIdShopIdReportsRouteImport } from './routes/_app.$tenantId.$shopId.reports'
import { Route as AppTenantIdShopIdSessionsRouteImport } from './routes/_app.$tenantId.$shopId.sessions'
import { Route as AppTenantIdShopIdDashboardsDashboardIdRouteImport } from './routes/_app.$tenantId.$shopId.dashboards_.$dashboardId'
import { Route as AppTenantIdShopIdEventsTabsRouteImport } from './routes/_app.$tenantId.$shopId.events._tabs'
import { Route as AppTenantIdShopIdProfilesTabsRouteImport } from './routes/_app.$tenantId.$shopId.profiles._tabs'
import { Route as AppTenantIdShopIdReportsReportIdRouteImport } from './routes/_app.$tenantId.$shopId.reports_.$reportId'
import { Route as AppTenantIdShopIdSessionsSessionIdRouteImport } from './routes/_app.$tenantId.$shopId.sessions_.$sessionId'
import { Route as AppTenantIdShopIdEventsTabsIndexRouteImport } from './routes/_app.$tenantId.$shopId.events._tabs.index'
import { Route as AppTenantIdShopIdEventsTabsConversionsRouteImport } from './routes/_app.$tenantId.$shopId.events._tabs.conversions'
import { Route as AppTenantIdShopIdEventsTabsEventsRouteImport } from './routes/_app.$tenantId.$shopId.events._tabs.events'
import { Route as AppTenantIdShopIdEventsTabsStatsRouteImport } from './routes/_app.$tenantId.$shopId.events._tabs.stats'
import { Route as AppTenantIdShopIdProfilesProfileIdTabsRouteImport } from './routes/_app.$tenantId.$shopId.profiles.$profileId._tabs'
import { Route as AppTenantIdShopIdProfilesTabsIndexRouteImport } from './routes/_app.$tenantId.$shopId.profiles._tabs.index'
import { Route as AppTenantIdShopIdProfilesTabsAnonymousRouteImport } from './routes/_app.$tenantId.$shopId.profiles._tabs.anonymous'
import { Route as AppTenantIdShopIdProfilesTabsIdentifiedRouteImport } from './routes/_app.$tenantId.$shopId.profiles._tabs.identified'
import { Route as AppTenantIdShopIdProfilesTabsPowerUsersRouteImport } from './routes/_app.$tenantId.$shopId.profiles._tabs.power-users'
import { Route as AppTenantIdShopIdProfilesProfileIdTabsIndexRouteImport } from './routes/_app.$tenantId.$shopId.profiles.$profileId._tabs.index'
import { Route as AppTenantIdShopIdProfilesProfileIdTabsEventsRouteImport } from './routes/_app.$tenantId.$shopId.profiles.$profileId._tabs.events'
import { Route as AppTenantIdShopIdProfilesProfileIdTabsSessionsRouteImport } from './routes/_app.$tenantId.$shopId.profiles.$profileId._tabs.sessions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTenantIdRoute = AppTenantIdRouteImport.update({
  id: '/$tenantId',
  path: '/$tenantId',
  getParentRoute: () => AppRoute,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthcheckRoute = ApiHealthcheckRouteImport.update({
  id: '/api/healthcheck',
  path: '/api/healthcheck',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetBadgeRoute = WidgetBadgeRouteImport.update({
  id: '/widget/badge',
  path: '/widget/badge',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetCounterRoute = WidgetCounterRouteImport.update({
  id: '/widget/counter',
  path: '/widget/counter',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetRealtimeRoute = WidgetRealtimeRouteImport.update({
  id: '/widget/realtime',
  path: '/widget/realtime',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetTestRoute = WidgetTestRouteImport.update({
  id: '/widget/test',
  path: '/widget/test',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTenantIdIndexRoute = AppTenantIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTenantIdRoute,
} as any)
const AppTenantIdShopIdRoute = AppTenantIdShopIdRouteImport.update({
  id: '/$shopId',
  path: '/$shopId',
  getParentRoute: () => AppTenantIdRoute,
} as any)
const AppTenantIdShopIdIndexRoute = AppTenantIdShopIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTenantIdShopIdRoute,
} as any)
const AppTenantIdShopIdDashboardsRoute =
  AppTenantIdShopIdDashboardsRouteImport.update({
    id: '/dashboards',
    path: '/dashboards',
    getParentRoute: () => AppTenantIdShopIdRoute,
  } as any)
const AppTenantIdShopIdInsightsRoute =
  AppTenantIdShopIdInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => AppTenantIdShopIdRoute,
  } as any)
const AppTenantIdShopIdPagesRoute = AppTenantIdShopIdPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AppTenantIdShopIdRoute,
} as any)
const AppTenantIdShopIdRealtimeRoute =
  AppTenantIdShopIdRealtimeRouteImport.update({
    id: '/realtime',
    path: '/realtime',
    getParentRoute: () => AppTenantIdShopIdRoute,
  } as any)
const AppTenantIdShopIdReportsRoute =
  AppTenantIdShopIdReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AppTenantIdShopIdRoute,
  } as any)
const AppTenantIdShopIdSessionsRoute =
  AppTenantIdShopIdSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AppTenantIdShopIdRoute,
  } as any)
const AppTenantIdShopIdDashboardsDashboardIdRoute =
  AppTenantIdShopIdDashboardsDashboardIdRouteImport.update({
    id: '/dashboards_/$dashboardId',
    path: '/dashboards/$dashboardId',
    getParentRoute: () => AppTenantIdShopIdRoute,
  } as any)
const AppTenantIdShopIdEventsTabsRoute =
  AppTenantIdShopIdEventsTabsRouteImport.update({
    id: '/events/_tabs',
    path: '/events',
    getParentRoute: () => AppTenantIdShopIdRoute,
  } as any)
const AppTenantIdShopIdProfilesTabsRoute =
  AppTenantIdShopIdProfilesTabsRouteImport.update({
    id: '/profiles/_tabs',
    path: '/profiles',
    getParentRoute: () => AppTenantIdShopIdRoute,
  } as any)
const AppTenantIdShopIdReportsReportIdRoute =
  AppTenantIdShopIdReportsReportIdRouteImport.update({
    id: '/reports_/$reportId',
    path: '/reports/$reportId',
    getParentRoute: () => AppTenantIdShopIdRoute,
  } as any)
const AppTenantIdShopIdSessionsSessionIdRoute =
  AppTenantIdShopIdSessionsSessionIdRouteImport.update({
    id: '/sessions_/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => AppTenantIdShopIdRoute,
  } as any)
const AppTenantIdShopIdEventsTabsIndexRoute =
  AppTenantIdShopIdEventsTabsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppTenantIdShopIdEventsTabsRoute,
  } as any)
const AppTenantIdShopIdEventsTabsConversionsRoute =
  AppTenantIdShopIdEventsTabsConversionsRouteImport.update({
    id: '/conversions',
    path: '/conversions',
    getParentRoute: () => AppTenantIdShopIdEventsTabsRoute,
  } as any)
const AppTenantIdShopIdEventsTabsEventsRoute =
  AppTenantIdShopIdEventsTabsEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AppTenantIdShopIdEventsTabsRoute,
  } as any)
const AppTenantIdShopIdEventsTabsStatsRoute =
  AppTenantIdShopIdEventsTabsStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => AppTenantIdShopIdEventsTabsRoute,
  } as any)
const AppTenantIdShopIdProfilesProfileIdTabsRoute =
  AppTenantIdShopIdProfilesProfileIdTabsRouteImport.update({
    id: '/profiles/$profileId/_tabs',
    path: '/profiles/$profileId',
    getParentRoute: () => AppTenantIdShopIdRoute,
  } as any)
const AppTenantIdShopIdProfilesTabsIndexRoute =
  AppTenantIdShopIdProfilesTabsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppTenantIdShopIdProfilesTabsRoute,
  } as any)
const AppTenantIdShopIdProfilesTabsAnonymousRoute =
  AppTenantIdShopIdProfilesTabsAnonymousRouteImport.update({
    id: '/anonymous',
    path: '/anonymous',
    getParentRoute: () => AppTenantIdShopIdProfilesTabsRoute,
  } as any)
const AppTenantIdShopIdProfilesTabsIdentifiedRoute =
  AppTenantIdShopIdProfilesTabsIdentifiedRouteImport.update({
    id: '/identified',
    path: '/identified',
    getParentRoute: () => AppTenantIdShopIdProfilesTabsRoute,
  } as any)
const AppTenantIdShopIdProfilesTabsPowerUsersRoute =
  AppTenantIdShopIdProfilesTabsPowerUsersRouteImport.update({
    id: '/power-users',
    path: '/power-users',
    getParentRoute: () => AppTenantIdShopIdProfilesTabsRoute,
  } as any)
const AppTenantIdShopIdProfilesProfileIdTabsIndexRoute =
  AppTenantIdShopIdProfilesProfileIdTabsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppTenantIdShopIdProfilesProfileIdTabsRoute,
  } as any)
const AppTenantIdShopIdProfilesProfileIdTabsEventsRoute =
  AppTenantIdShopIdProfilesProfileIdTabsEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AppTenantIdShopIdProfilesProfileIdTabsRoute,
  } as any)
const AppTenantIdShopIdProfilesProfileIdTabsSessionsRoute =
  AppTenantIdShopIdProfilesProfileIdTabsSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AppTenantIdShopIdProfilesProfileIdTabsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$tenantId': typeof AppTenantIdRouteWithChildren
  '/api/config': typeof ApiConfigRoute
  '/api/healthcheck': typeof ApiHealthcheckRoute
  '/widget/badge': typeof WidgetBadgeRoute
  '/widget/counter': typeof WidgetCounterRoute
  '/widget/realtime': typeof WidgetRealtimeRoute
  '/widget/test': typeof WidgetTestRoute
  '/$tenantId/$shopId': typeof AppTenantIdShopIdRouteWithChildren
  '/$tenantId/': typeof AppTenantIdIndexRoute
  '/$tenantId/$shopId/dashboards': typeof AppTenantIdShopIdDashboardsRoute
  '/$tenantId/$shopId/insights': typeof AppTenantIdShopIdInsightsRoute
  '/$tenantId/$shopId/pages': typeof AppTenantIdShopIdPagesRoute
  '/$tenantId/$shopId/realtime': typeof AppTenantIdShopIdRealtimeRoute
  '/$tenantId/$shopId/reports': typeof AppTenantIdShopIdReportsRoute
  '/$tenantId/$shopId/sessions': typeof AppTenantIdShopIdSessionsRoute
  '/$tenantId/$shopId/': typeof AppTenantIdShopIdIndexRoute
  '/$tenantId/$shopId/dashboards/$dashboardId': typeof AppTenantIdShopIdDashboardsDashboardIdRoute
  '/$tenantId/$shopId/events': typeof AppTenantIdShopIdEventsTabsRouteWithChildren
  '/$tenantId/$shopId/profiles': typeof AppTenantIdShopIdProfilesTabsRouteWithChildren
  '/$tenantId/$shopId/reports/$reportId': typeof AppTenantIdShopIdReportsReportIdRoute
  '/$tenantId/$shopId/sessions/$sessionId': typeof AppTenantIdShopIdSessionsSessionIdRoute
  '/$tenantId/$shopId/events/conversions': typeof AppTenantIdShopIdEventsTabsConversionsRoute
  '/$tenantId/$shopId/events/events': typeof AppTenantIdShopIdEventsTabsEventsRoute
  '/$tenantId/$shopId/events/stats': typeof AppTenantIdShopIdEventsTabsStatsRoute
  '/$tenantId/$shopId/profiles/$profileId': typeof AppTenantIdShopIdProfilesProfileIdTabsRouteWithChildren
  '/$tenantId/$shopId/profiles/anonymous': typeof AppTenantIdShopIdProfilesTabsAnonymousRoute
  '/$tenantId/$shopId/profiles/identified': typeof AppTenantIdShopIdProfilesTabsIdentifiedRoute
  '/$tenantId/$shopId/profiles/power-users': typeof AppTenantIdShopIdProfilesTabsPowerUsersRoute
  '/$tenantId/$shopId/events/': typeof AppTenantIdShopIdEventsTabsIndexRoute
  '/$tenantId/$shopId/profiles/': typeof AppTenantIdShopIdProfilesTabsIndexRoute
  '/$tenantId/$shopId/profiles/$profileId/events': typeof AppTenantIdShopIdProfilesProfileIdTabsEventsRoute
  '/$tenantId/$shopId/profiles/$profileId/sessions': typeof AppTenantIdShopIdProfilesProfileIdTabsSessionsRoute
  '/$tenantId/$shopId/profiles/$profileId/': typeof AppTenantIdShopIdProfilesProfileIdTabsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/config': typeof ApiConfigRoute
  '/api/healthcheck': typeof ApiHealthcheckRoute
  '/widget/badge': typeof WidgetBadgeRoute
  '/widget/counter': typeof WidgetCounterRoute
  '/widget/realtime': typeof WidgetRealtimeRoute
  '/widget/test': typeof WidgetTestRoute
  '/$tenantId': typeof AppTenantIdIndexRoute
  '/$tenantId/$shopId/dashboards': typeof AppTenantIdShopIdDashboardsRoute
  '/$tenantId/$shopId/insights': typeof AppTenantIdShopIdInsightsRoute
  '/$tenantId/$shopId/pages': typeof AppTenantIdShopIdPagesRoute
  '/$tenantId/$shopId/realtime': typeof AppTenantIdShopIdRealtimeRoute
  '/$tenantId/$shopId/reports': typeof AppTenantIdShopIdReportsRoute
  '/$tenantId/$shopId/sessions': typeof AppTenantIdShopIdSessionsRoute
  '/$tenantId/$shopId': typeof AppTenantIdShopIdIndexRoute
  '/$tenantId/$shopId/dashboards/$dashboardId': typeof AppTenantIdShopIdDashboardsDashboardIdRoute
  '/$tenantId/$shopId/reports/$reportId': typeof AppTenantIdShopIdReportsReportIdRoute
  '/$tenantId/$shopId/sessions/$sessionId': typeof AppTenantIdShopIdSessionsSessionIdRoute
  '/$tenantId/$shopId/events/conversions': typeof AppTenantIdShopIdEventsTabsConversionsRoute
  '/$tenantId/$shopId/events/events': typeof AppTenantIdShopIdEventsTabsEventsRoute
  '/$tenantId/$shopId/events/stats': typeof AppTenantIdShopIdEventsTabsStatsRoute
  '/$tenantId/$shopId/profiles/anonymous': typeof AppTenantIdShopIdProfilesTabsAnonymousRoute
  '/$tenantId/$shopId/profiles/identified': typeof AppTenantIdShopIdProfilesTabsIdentifiedRoute
  '/$tenantId/$shopId/profiles/power-users': typeof AppTenantIdShopIdProfilesTabsPowerUsersRoute
  '/$tenantId/$shopId/events': typeof AppTenantIdShopIdEventsTabsIndexRoute
  '/$tenantId/$shopId/profiles': typeof AppTenantIdShopIdProfilesTabsIndexRoute
  '/$tenantId/$shopId/profiles/$profileId/events': typeof AppTenantIdShopIdProfilesProfileIdTabsEventsRoute
  '/$tenantId/$shopId/profiles/$profileId/sessions': typeof AppTenantIdShopIdProfilesProfileIdTabsSessionsRoute
  '/$tenantId/$shopId/profiles/$profileId': typeof AppTenantIdShopIdProfilesProfileIdTabsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/$tenantId': typeof AppTenantIdRouteWithChildren
  '/api/config': typeof ApiConfigRoute
  '/api/healthcheck': typeof ApiHealthcheckRoute
  '/widget/badge': typeof WidgetBadgeRoute
  '/widget/counter': typeof WidgetCounterRoute
  '/widget/realtime': typeof WidgetRealtimeRoute
  '/widget/test': typeof WidgetTestRoute
  '/_app/$tenantId/$shopId': typeof AppTenantIdShopIdRouteWithChildren
  '/_app/$tenantId/': typeof AppTenantIdIndexRoute
  '/_app/$tenantId/$shopId/dashboards': typeof AppTenantIdShopIdDashboardsRoute
  '/_app/$tenantId/$shopId/insights': typeof AppTenantIdShopIdInsightsRoute
  '/_app/$tenantId/$shopId/pages': typeof AppTenantIdShopIdPagesRoute
  '/_app/$tenantId/$shopId/realtime': typeof AppTenantIdShopIdRealtimeRoute
  '/_app/$tenantId/$shopId/reports': typeof AppTenantIdShopIdReportsRoute
  '/_app/$tenantId/$shopId/sessions': typeof AppTenantIdShopIdSessionsRoute
  '/_app/$tenantId/$shopId/': typeof AppTenantIdShopIdIndexRoute
  '/_app/$tenantId/$shopId/dashboards_/$dashboardId': typeof AppTenantIdShopIdDashboardsDashboardIdRoute
  '/_app/$tenantId/$shopId/events/_tabs': typeof AppTenantIdShopIdEventsTabsRouteWithChildren
  '/_app/$tenantId/$shopId/profiles/_tabs': typeof AppTenantIdShopIdProfilesTabsRouteWithChildren
  '/_app/$tenantId/$shopId/reports_/$reportId': typeof AppTenantIdShopIdReportsReportIdRoute
  '/_app/$tenantId/$shopId/sessions_/$sessionId': typeof AppTenantIdShopIdSessionsSessionIdRoute
  '/_app/$tenantId/$shopId/events/_tabs/conversions': typeof AppTenantIdShopIdEventsTabsConversionsRoute
  '/_app/$tenantId/$shopId/events/_tabs/events': typeof AppTenantIdShopIdEventsTabsEventsRoute
  '/_app/$tenantId/$shopId/events/_tabs/stats': typeof AppTenantIdShopIdEventsTabsStatsRoute
  '/_app/$tenantId/$shopId/profiles/$profileId/_tabs': typeof AppTenantIdShopIdProfilesProfileIdTabsRouteWithChildren
  '/_app/$tenantId/$shopId/profiles/_tabs/anonymous': typeof AppTenantIdShopIdProfilesTabsAnonymousRoute
  '/_app/$tenantId/$shopId/profiles/_tabs/identified': typeof AppTenantIdShopIdProfilesTabsIdentifiedRoute
  '/_app/$tenantId/$shopId/profiles/_tabs/power-users': typeof AppTenantIdShopIdProfilesTabsPowerUsersRoute
  '/_app/$tenantId/$shopId/events/_tabs/': typeof AppTenantIdShopIdEventsTabsIndexRoute
  '/_app/$tenantId/$shopId/profiles/_tabs/': typeof AppTenantIdShopIdProfilesTabsIndexRoute
  '/_app/$tenantId/$shopId/profiles/$profileId/_tabs/events': typeof AppTenantIdShopIdProfilesProfileIdTabsEventsRoute
  '/_app/$tenantId/$shopId/profiles/$profileId/_tabs/sessions': typeof AppTenantIdShopIdProfilesProfileIdTabsSessionsRoute
  '/_app/$tenantId/$shopId/profiles/$profileId/_tabs/': typeof AppTenantIdShopIdProfilesProfileIdTabsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$tenantId'
    | '/api/config'
    | '/api/healthcheck'
    | '/widget/badge'
    | '/widget/counter'
    | '/widget/realtime'
    | '/widget/test'
    | '/$tenantId/$shopId'
    | '/$tenantId/'
    | '/$tenantId/$shopId/dashboards'
    | '/$tenantId/$shopId/insights'
    | '/$tenantId/$shopId/pages'
    | '/$tenantId/$shopId/realtime'
    | '/$tenantId/$shopId/reports'
    | '/$tenantId/$shopId/sessions'
    | '/$tenantId/$shopId/'
    | '/$tenantId/$shopId/dashboards/$dashboardId'
    | '/$tenantId/$shopId/events'
    | '/$tenantId/$shopId/profiles'
    | '/$tenantId/$shopId/reports/$reportId'
    | '/$tenantId/$shopId/sessions/$sessionId'
    | '/$tenantId/$shopId/events/conversions'
    | '/$tenantId/$shopId/events/events'
    | '/$tenantId/$shopId/events/stats'
    | '/$tenantId/$shopId/profiles/$profileId'
    | '/$tenantId/$shopId/profiles/anonymous'
    | '/$tenantId/$shopId/profiles/identified'
    | '/$tenantId/$shopId/profiles/power-users'
    | '/$tenantId/$shopId/events/'
    | '/$tenantId/$shopId/profiles/'
    | '/$tenantId/$shopId/profiles/$profileId/events'
    | '/$tenantId/$shopId/profiles/$profileId/sessions'
    | '/$tenantId/$shopId/profiles/$profileId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/config'
    | '/api/healthcheck'
    | '/widget/badge'
    | '/widget/counter'
    | '/widget/realtime'
    | '/widget/test'
    | '/$tenantId'
    | '/$tenantId/$shopId/dashboards'
    | '/$tenantId/$shopId/insights'
    | '/$tenantId/$shopId/pages'
    | '/$tenantId/$shopId/realtime'
    | '/$tenantId/$shopId/reports'
    | '/$tenantId/$shopId/sessions'
    | '/$tenantId/$shopId'
    | '/$tenantId/$shopId/dashboards/$dashboardId'
    | '/$tenantId/$shopId/reports/$reportId'
    | '/$tenantId/$shopId/sessions/$sessionId'
    | '/$tenantId/$shopId/events/conversions'
    | '/$tenantId/$shopId/events/events'
    | '/$tenantId/$shopId/events/stats'
    | '/$tenantId/$shopId/profiles/anonymous'
    | '/$tenantId/$shopId/profiles/identified'
    | '/$tenantId/$shopId/profiles/power-users'
    | '/$tenantId/$shopId/events'
    | '/$tenantId/$shopId/profiles'
    | '/$tenantId/$shopId/profiles/$profileId/events'
    | '/$tenantId/$shopId/profiles/$profileId/sessions'
    | '/$tenantId/$shopId/profiles/$profileId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/$tenantId'
    | '/api/config'
    | '/api/healthcheck'
    | '/widget/badge'
    | '/widget/counter'
    | '/widget/realtime'
    | '/widget/test'
    | '/_app/$tenantId/$shopId'
    | '/_app/$tenantId/'
    | '/_app/$tenantId/$shopId/dashboards'
    | '/_app/$tenantId/$shopId/insights'
    | '/_app/$tenantId/$shopId/pages'
    | '/_app/$tenantId/$shopId/realtime'
    | '/_app/$tenantId/$shopId/reports'
    | '/_app/$tenantId/$shopId/sessions'
    | '/_app/$tenantId/$shopId/'
    | '/_app/$tenantId/$shopId/dashboards_/$dashboardId'
    | '/_app/$tenantId/$shopId/events/_tabs'
    | '/_app/$tenantId/$shopId/profiles/_tabs'
    | '/_app/$tenantId/$shopId/reports_/$reportId'
    | '/_app/$tenantId/$shopId/sessions_/$sessionId'
    | '/_app/$tenantId/$shopId/events/_tabs/conversions'
    | '/_app/$tenantId/$shopId/events/_tabs/events'
    | '/_app/$tenantId/$shopId/events/_tabs/stats'
    | '/_app/$tenantId/$shopId/profiles/$profileId/_tabs'
    | '/_app/$tenantId/$shopId/profiles/_tabs/anonymous'
    | '/_app/$tenantId/$shopId/profiles/_tabs/identified'
    | '/_app/$tenantId/$shopId/profiles/_tabs/power-users'
    | '/_app/$tenantId/$shopId/events/_tabs/'
    | '/_app/$tenantId/$shopId/profiles/_tabs/'
    | '/_app/$tenantId/$shopId/profiles/$profileId/_tabs/events'
    | '/_app/$tenantId/$shopId/profiles/$profileId/_tabs/sessions'
    | '/_app/$tenantId/$shopId/profiles/$profileId/_tabs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiConfigRoute: typeof ApiConfigRoute
  ApiHealthcheckRoute: typeof ApiHealthcheckRoute
  WidgetBadgeRoute: typeof WidgetBadgeRoute
  WidgetCounterRoute: typeof WidgetCounterRoute
  WidgetRealtimeRoute: typeof WidgetRealtimeRoute
  WidgetTestRoute: typeof WidgetTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$tenantId': {
      id: '/_app/$tenantId'
      path: '/$tenantId'
      fullPath: '/$tenantId'
      preLoaderRoute: typeof AppTenantIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/healthcheck': {
      id: '/api/healthcheck'
      path: '/api/healthcheck'
      fullPath: '/api/healthcheck'
      preLoaderRoute: typeof ApiHealthcheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget/badge': {
      id: '/widget/badge'
      path: '/widget/badge'
      fullPath: '/widget/badge'
      preLoaderRoute: typeof WidgetBadgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget/counter': {
      id: '/widget/counter'
      path: '/widget/counter'
      fullPath: '/widget/counter'
      preLoaderRoute: typeof WidgetCounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget/realtime': {
      id: '/widget/realtime'
      path: '/widget/realtime'
      fullPath: '/widget/realtime'
      preLoaderRoute: typeof WidgetRealtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget/test': {
      id: '/widget/test'
      path: '/widget/test'
      fullPath: '/widget/test'
      preLoaderRoute: typeof WidgetTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$tenantId/': {
      id: '/_app/$tenantId/'
      path: '/'
      fullPath: '/$tenantId/'
      preLoaderRoute: typeof AppTenantIdIndexRouteImport
      parentRoute: typeof AppTenantIdRoute
    }
    '/_app/$tenantId/$shopId': {
      id: '/_app/$tenantId/$shopId'
      path: '/$shopId'
      fullPath: '/$tenantId/$shopId'
      preLoaderRoute: typeof AppTenantIdShopIdRouteImport
      parentRoute: typeof AppTenantIdRoute
    }
    '/_app/$tenantId/$shopId/': {
      id: '/_app/$tenantId/$shopId/'
      path: '/'
      fullPath: '/$tenantId/$shopId/'
      preLoaderRoute: typeof AppTenantIdShopIdIndexRouteImport
      parentRoute: typeof AppTenantIdShopIdRoute
    }
    '/_app/$tenantId/$shopId/dashboards': {
      id: '/_app/$tenantId/$shopId/dashboards'
      path: '/dashboards'
      fullPath: '/$tenantId/$shopId/dashboards'
      preLoaderRoute: typeof AppTenantIdShopIdDashboardsRouteImport
      parentRoute: typeof AppTenantIdShopIdRoute
    }
    '/_app/$tenantId/$shopId/insights': {
      id: '/_app/$tenantId/$shopId/insights'
      path: '/insights'
      fullPath: '/$tenantId/$shopId/insights'
      preLoaderRoute: typeof AppTenantIdShopIdInsightsRouteImport
      parentRoute: typeof AppTenantIdShopIdRoute
    }
    '/_app/$tenantId/$shopId/pages': {
      id: '/_app/$tenantId/$shopId/pages'
      path: '/pages'
      fullPath: '/$tenantId/$shopId/pages'
      preLoaderRoute: typeof AppTenantIdShopIdPagesRouteImport
      parentRoute: typeof AppTenantIdShopIdRoute
    }
    '/_app/$tenantId/$shopId/realtime': {
      id: '/_app/$tenantId/$shopId/realtime'
      path: '/realtime'
      fullPath: '/$tenantId/$shopId/realtime'
      preLoaderRoute: typeof AppTenantIdShopIdRealtimeRouteImport
      parentRoute: typeof AppTenantIdShopIdRoute
    }
    '/_app/$tenantId/$shopId/reports': {
      id: '/_app/$tenantId/$shopId/reports'
      path: '/reports'
      fullPath: '/$tenantId/$shopId/reports'
      preLoaderRoute: typeof AppTenantIdShopIdReportsRouteImport
      parentRoute: typeof AppTenantIdShopIdRoute
    }
    '/_app/$tenantId/$shopId/sessions': {
      id: '/_app/$tenantId/$shopId/sessions'
      path: '/sessions'
      fullPath: '/$tenantId/$shopId/sessions'
      preLoaderRoute: typeof AppTenantIdShopIdSessionsRouteImport
      parentRoute: typeof AppTenantIdShopIdRoute
    }
    '/_app/$tenantId/$shopId/dashboards_/$dashboardId': {
      id: '/_app/$tenantId/$shopId/dashboards_/$dashboardId'
      path: '/dashboards/$dashboardId'
      fullPath: '/$tenantId/$shopId/dashboards/$dashboardId'
      preLoaderRoute: typeof AppTenantIdShopIdDashboardsDashboardIdRouteImport
      parentRoute: typeof AppTenantIdShopIdRoute
    }
    '/_app/$tenantId/$shopId/events/_tabs': {
      id: '/_app/$tenantId/$shopId/events/_tabs'
      path: '/events'
      fullPath: '/$tenantId/$shopId/events'
      preLoaderRoute: typeof AppTenantIdShopIdEventsTabsRouteImport
      parentRoute: typeof AppTenantIdShopIdRoute
    }
    '/_app/$tenantId/$shopId/profiles/_tabs': {
      id: '/_app/$tenantId/$shopId/profiles/_tabs'
      path: '/profiles'
      fullPath: '/$tenantId/$shopId/profiles'
      preLoaderRoute: typeof AppTenantIdShopIdProfilesTabsRouteImport
      parentRoute: typeof AppTenantIdShopIdRoute
    }
    '/_app/$tenantId/$shopId/reports_/$reportId': {
      id: '/_app/$tenantId/$shopId/reports_/$reportId'
      path: '/reports/$reportId'
      fullPath: '/$tenantId/$shopId/reports/$reportId'
      preLoaderRoute: typeof AppTenantIdShopIdReportsReportIdRouteImport
      parentRoute: typeof AppTenantIdShopIdRoute
    }
    '/_app/$tenantId/$shopId/sessions_/$sessionId': {
      id: '/_app/$tenantId/$shopId/sessions_/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/$tenantId/$shopId/sessions/$sessionId'
      preLoaderRoute: typeof AppTenantIdShopIdSessionsSessionIdRouteImport
      parentRoute: typeof AppTenantIdShopIdRoute
    }
    '/_app/$tenantId/$shopId/events/_tabs/': {
      id: '/_app/$tenantId/$shopId/events/_tabs/'
      path: '/'
      fullPath: '/$tenantId/$shopId/events/'
      preLoaderRoute: typeof AppTenantIdShopIdEventsTabsIndexRouteImport
      parentRoute: typeof AppTenantIdShopIdEventsTabsRoute
    }
    '/_app/$tenantId/$shopId/events/_tabs/conversions': {
      id: '/_app/$tenantId/$shopId/events/_tabs/conversions'
      path: '/conversions'
      fullPath: '/$tenantId/$shopId/events/conversions'
      preLoaderRoute: typeof AppTenantIdShopIdEventsTabsConversionsRouteImport
      parentRoute: typeof AppTenantIdShopIdEventsTabsRoute
    }
    '/_app/$tenantId/$shopId/events/_tabs/events': {
      id: '/_app/$tenantId/$shopId/events/_tabs/events'
      path: '/events'
      fullPath: '/$tenantId/$shopId/events/events'
      preLoaderRoute: typeof AppTenantIdShopIdEventsTabsEventsRouteImport
      parentRoute: typeof AppTenantIdShopIdEventsTabsRoute
    }
    '/_app/$tenantId/$shopId/events/_tabs/stats': {
      id: '/_app/$tenantId/$shopId/events/_tabs/stats'
      path: '/stats'
      fullPath: '/$tenantId/$shopId/events/stats'
      preLoaderRoute: typeof AppTenantIdShopIdEventsTabsStatsRouteImport
      parentRoute: typeof AppTenantIdShopIdEventsTabsRoute
    }
    '/_app/$tenantId/$shopId/profiles/$profileId/_tabs': {
      id: '/_app/$tenantId/$shopId/profiles/$profileId/_tabs'
      path: '/profiles/$profileId'
      fullPath: '/$tenantId/$shopId/profiles/$profileId'
      preLoaderRoute: typeof AppTenantIdShopIdProfilesProfileIdTabsRouteImport
      parentRoute: typeof AppTenantIdShopIdRoute
    }
    '/_app/$tenantId/$shopId/profiles/_tabs/': {
      id: '/_app/$tenantId/$shopId/profiles/_tabs/'
      path: '/'
      fullPath: '/$tenantId/$shopId/profiles/'
      preLoaderRoute: typeof AppTenantIdShopIdProfilesTabsIndexRouteImport
      parentRoute: typeof AppTenantIdShopIdProfilesTabsRoute
    }
    '/_app/$tenantId/$shopId/profiles/_tabs/anonymous': {
      id: '/_app/$tenantId/$shopId/profiles/_tabs/anonymous'
      path: '/anonymous'
      fullPath: '/$tenantId/$shopId/profiles/anonymous'
      preLoaderRoute: typeof AppTenantIdShopIdProfilesTabsAnonymousRouteImport
      parentRoute: typeof AppTenantIdShopIdProfilesTabsRoute
    }
    '/_app/$tenantId/$shopId/profiles/_tabs/identified': {
      id: '/_app/$tenantId/$shopId/profiles/_tabs/identified'
      path: '/identified'
      fullPath: '/$tenantId/$shopId/profiles/identified'
      preLoaderRoute: typeof AppTenantIdShopIdProfilesTabsIdentifiedRouteImport
      parentRoute: typeof AppTenantIdShopIdProfilesTabsRoute
    }
    '/_app/$tenantId/$shopId/profiles/_tabs/power-users': {
      id: '/_app/$tenantId/$shopId/profiles/_tabs/power-users'
      path: '/power-users'
      fullPath: '/$tenantId/$shopId/profiles/power-users'
      preLoaderRoute: typeof AppTenantIdShopIdProfilesTabsPowerUsersRouteImport
      parentRoute: typeof AppTenantIdShopIdProfilesTabsRoute
    }
    '/_app/$tenantId/$shopId/profiles/$profileId/_tabs/': {
      id: '/_app/$tenantId/$shopId/profiles/$profileId/_tabs/'
      path: '/'
      fullPath: '/$tenantId/$shopId/profiles/$profileId/'
      preLoaderRoute: typeof AppTenantIdShopIdProfilesProfileIdTabsIndexRouteImport
      parentRoute: typeof AppTenantIdShopIdProfilesProfileIdTabsRoute
    }
    '/_app/$tenantId/$shopId/profiles/$profileId/_tabs/events': {
      id: '/_app/$tenantId/$shopId/profiles/$profileId/_tabs/events'
      path: '/events'
      fullPath: '/$tenantId/$shopId/profiles/$profileId/events'
      preLoaderRoute: typeof AppTenantIdShopIdProfilesProfileIdTabsEventsRouteImport
      parentRoute: typeof AppTenantIdShopIdProfilesProfileIdTabsRoute
    }
    '/_app/$tenantId/$shopId/profiles/$profileId/_tabs/sessions': {
      id: '/_app/$tenantId/$shopId/profiles/$profileId/_tabs/sessions'
      path: '/sessions'
      fullPath: '/$tenantId/$shopId/profiles/$profileId/sessions'
      preLoaderRoute: typeof AppTenantIdShopIdProfilesProfileIdTabsSessionsRouteImport
      parentRoute: typeof AppTenantIdShopIdProfilesProfileIdTabsRoute
    }
  }
}

interface AppTenantIdShopIdEventsTabsRouteChildren {
  AppTenantIdShopIdEventsTabsConversionsRoute: typeof AppTenantIdShopIdEventsTabsConversionsRoute
  AppTenantIdShopIdEventsTabsEventsRoute: typeof AppTenantIdShopIdEventsTabsEventsRoute
  AppTenantIdShopIdEventsTabsStatsRoute: typeof AppTenantIdShopIdEventsTabsStatsRoute
  AppTenantIdShopIdEventsTabsIndexRoute: typeof AppTenantIdShopIdEventsTabsIndexRoute
}

const AppTenantIdShopIdEventsTabsRouteChildren: AppTenantIdShopIdEventsTabsRouteChildren =
  {
    AppTenantIdShopIdEventsTabsConversionsRoute:
      AppTenantIdShopIdEventsTabsConversionsRoute,
    AppTenantIdShopIdEventsTabsEventsRoute:
      AppTenantIdShopIdEventsTabsEventsRoute,
    AppTenantIdShopIdEventsTabsStatsRoute:
      AppTenantIdShopIdEventsTabsStatsRoute,
    AppTenantIdShopIdEventsTabsIndexRoute:
      AppTenantIdShopIdEventsTabsIndexRoute,
  }

const AppTenantIdShopIdEventsTabsRouteWithChildren =
  AppTenantIdShopIdEventsTabsRoute._addFileChildren(
    AppTenantIdShopIdEventsTabsRouteChildren,
  )

interface AppTenantIdShopIdProfilesTabsRouteChildren {
  AppTenantIdShopIdProfilesTabsAnonymousRoute: typeof AppTenantIdShopIdProfilesTabsAnonymousRoute
  AppTenantIdShopIdProfilesTabsIdentifiedRoute: typeof AppTenantIdShopIdProfilesTabsIdentifiedRoute
  AppTenantIdShopIdProfilesTabsPowerUsersRoute: typeof AppTenantIdShopIdProfilesTabsPowerUsersRoute
  AppTenantIdShopIdProfilesTabsIndexRoute: typeof AppTenantIdShopIdProfilesTabsIndexRoute
}

const AppTenantIdShopIdProfilesTabsRouteChildren: AppTenantIdShopIdProfilesTabsRouteChildren =
  {
    AppTenantIdShopIdProfilesTabsAnonymousRoute:
      AppTenantIdShopIdProfilesTabsAnonymousRoute,
    AppTenantIdShopIdProfilesTabsIdentifiedRoute:
      AppTenantIdShopIdProfilesTabsIdentifiedRoute,
    AppTenantIdShopIdProfilesTabsPowerUsersRoute:
      AppTenantIdShopIdProfilesTabsPowerUsersRoute,
    AppTenantIdShopIdProfilesTabsIndexRoute:
      AppTenantIdShopIdProfilesTabsIndexRoute,
  }

const AppTenantIdShopIdProfilesTabsRouteWithChildren =
  AppTenantIdShopIdProfilesTabsRoute._addFileChildren(
    AppTenantIdShopIdProfilesTabsRouteChildren,
  )

interface AppTenantIdShopIdProfilesProfileIdTabsRouteChildren {
  AppTenantIdShopIdProfilesProfileIdTabsEventsRoute: typeof AppTenantIdShopIdProfilesProfileIdTabsEventsRoute
  AppTenantIdShopIdProfilesProfileIdTabsSessionsRoute: typeof AppTenantIdShopIdProfilesProfileIdTabsSessionsRoute
  AppTenantIdShopIdProfilesProfileIdTabsIndexRoute: typeof AppTenantIdShopIdProfilesProfileIdTabsIndexRoute
}

const AppTenantIdShopIdProfilesProfileIdTabsRouteChildren: AppTenantIdShopIdProfilesProfileIdTabsRouteChildren =
  {
    AppTenantIdShopIdProfilesProfileIdTabsEventsRoute:
      AppTenantIdShopIdProfilesProfileIdTabsEventsRoute,
    AppTenantIdShopIdProfilesProfileIdTabsSessionsRoute:
      AppTenantIdShopIdProfilesProfileIdTabsSessionsRoute,
    AppTenantIdShopIdProfilesProfileIdTabsIndexRoute:
      AppTenantIdShopIdProfilesProfileIdTabsIndexRoute,
  }

const AppTenantIdShopIdProfilesProfileIdTabsRouteWithChildren =
  AppTenantIdShopIdProfilesProfileIdTabsRoute._addFileChildren(
    AppTenantIdShopIdProfilesProfileIdTabsRouteChildren,
  )

interface AppTenantIdShopIdRouteChildren {
  AppTenantIdShopIdDashboardsRoute: typeof AppTenantIdShopIdDashboardsRoute
  AppTenantIdShopIdInsightsRoute: typeof AppTenantIdShopIdInsightsRoute
  AppTenantIdShopIdPagesRoute: typeof AppTenantIdShopIdPagesRoute
  AppTenantIdShopIdRealtimeRoute: typeof AppTenantIdShopIdRealtimeRoute
  AppTenantIdShopIdReportsRoute: typeof AppTenantIdShopIdReportsRoute
  AppTenantIdShopIdSessionsRoute: typeof AppTenantIdShopIdSessionsRoute
  AppTenantIdShopIdIndexRoute: typeof AppTenantIdShopIdIndexRoute
  AppTenantIdShopIdDashboardsDashboardIdRoute: typeof AppTenantIdShopIdDashboardsDashboardIdRoute
  AppTenantIdShopIdEventsTabsRoute: typeof AppTenantIdShopIdEventsTabsRouteWithChildren
  AppTenantIdShopIdProfilesTabsRoute: typeof AppTenantIdShopIdProfilesTabsRouteWithChildren
  AppTenantIdShopIdReportsReportIdRoute: typeof AppTenantIdShopIdReportsReportIdRoute
  AppTenantIdShopIdSessionsSessionIdRoute: typeof AppTenantIdShopIdSessionsSessionIdRoute
  AppTenantIdShopIdProfilesProfileIdTabsRoute: typeof AppTenantIdShopIdProfilesProfileIdTabsRouteWithChildren
}

const AppTenantIdShopIdRouteChildren: AppTenantIdShopIdRouteChildren = {
  AppTenantIdShopIdDashboardsRoute: AppTenantIdShopIdDashboardsRoute,
  AppTenantIdShopIdInsightsRoute: AppTenantIdShopIdInsightsRoute,
  AppTenantIdShopIdPagesRoute: AppTenantIdShopIdPagesRoute,
  AppTenantIdShopIdRealtimeRoute: AppTenantIdShopIdRealtimeRoute,
  AppTenantIdShopIdReportsRoute: AppTenantIdShopIdReportsRoute,
  AppTenantIdShopIdSessionsRoute: AppTenantIdShopIdSessionsRoute,
  AppTenantIdShopIdIndexRoute: AppTenantIdShopIdIndexRoute,
  AppTenantIdShopIdDashboardsDashboardIdRoute:
    AppTenantIdShopIdDashboardsDashboardIdRoute,
  AppTenantIdShopIdEventsTabsRoute:
    AppTenantIdShopIdEventsTabsRouteWithChildren,
  AppTenantIdShopIdProfilesTabsRoute:
    AppTenantIdShopIdProfilesTabsRouteWithChildren,
  AppTenantIdShopIdReportsReportIdRoute: AppTenantIdShopIdReportsReportIdRoute,
  AppTenantIdShopIdSessionsSessionIdRoute:
    AppTenantIdShopIdSessionsSessionIdRoute,
  AppTenantIdShopIdProfilesProfileIdTabsRoute:
    AppTenantIdShopIdProfilesProfileIdTabsRouteWithChildren,
}

const AppTenantIdShopIdRouteWithChildren =
  AppTenantIdShopIdRoute._addFileChildren(AppTenantIdShopIdRouteChildren)

interface AppTenantIdRouteChildren {
  AppTenantIdShopIdRoute: typeof AppTenantIdShopIdRouteWithChildren
  AppTenantIdIndexRoute: typeof AppTenantIdIndexRoute
}

const AppTenantIdRouteChildren: AppTenantIdRouteChildren = {
  AppTenantIdShopIdRoute: AppTenantIdShopIdRouteWithChildren,
  AppTenantIdIndexRoute: AppTenantIdIndexRoute,
}

const AppTenantIdRouteWithChildren = AppTenantIdRoute._addFileChildren(
  AppTenantIdRouteChildren,
)

interface AppRouteChildren {
  AppTenantIdRoute: typeof AppTenantIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppTenantIdRoute: AppTenantIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiConfigRoute: ApiConfigRoute,
  ApiHealthcheckRoute: ApiHealthcheckRoute,
  WidgetBadgeRoute: WidgetBadgeRoute,
  WidgetCounterRoute: WidgetCounterRoute,
  WidgetRealtimeRoute: WidgetRealtimeRoute,
  WidgetTestRoute: WidgetTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
